Fix clippy::items_after_test_module warning
```
error: items after a test module
   --> tf_rosrust/src/transforms.rs:136:1
    |
136 |   mod test {
    |   ^^^^^^^^
...
217 | / pub(crate) fn to_transform_stamped(
218 | |     tf: Transform,
219 | |     from: std::string::String,
220 | |     to: std::string::String,
221 | |     time: rosrust::Time,
222 | | ) -> TransformStamped {
    | |_____________________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_test_module
    = note: `-D clippy::items-after-test-module` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::items_after_test_module)]`
    = help: move the items to before the test module was defined
```